# Uncomment this if your project is hosted on GitHub:
github_url = "https://github.com/mikapfl/once/"

[version]
current = "0.1.0"

# Example of a semver regexp.
# Make sure this matches current_version before
# using tbump
regex = '''
  (?P<major>\d+)
  \.
  (?P<minor>\d+)
  \.
  (?P<patch>\d+)
  '''

[git]
message_template = "Release version {new_version}"
tag_template = "v{new_version}"

# For each file to patch, add a [[file]] config
# section containing the path of the file, relative to the
# tbump.toml location.
[[file]]
src = "setup.cfg"
search = 'version = {current_version}'

[[file]]
src = "once/__init__.py"
search = '__version__ = "{current_version}"'

# You can specify a list of commands to
# run after the files have been patched
# and before the git commit is made

[[before_commit]]
name = "lint"
cmd = "make lint"

[[before_commit]]
name = "update changelog"
cmd = "venv/bin/python update_changelog.py {new_version}"

# Or run some commands after the git tag and the branch
# have been pushed:

[[after_push]]
name = "release on github"
cmd = "gh release create --repo mikapfl/once v{new_version} --title 'once Version {new_version}' --notes-file .changelog_latest_version.rst"
